name: Build C++ Application (Multi-Platform)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build on ${{ matrix.os }}
      run: g++ main.cpp file.cpp chrono.cpp calculator.cpp todolist.cpp -o ToolSoftware${{ matrix.os == 'windows-latest' && '.exe' || '' }}
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ToolSoftware-${{ matrix.os }}
        path: ToolSoftware*